services:
  valkey:
    image: valkey/valkey:8-alpine
    container_name: valkey-server
    env_file:
      - ./.env
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data/valkey

  pg:
    image: postgres:16-alpine
    container_name: pg-server
    env_file:
      - ./.env
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/data/db'

    # Allows app to wait for container boostrap https://docs.docker.com/reference/dockerfile/#healthcheck

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d appdb"]
      start_period: 3s

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - ./.env
    ports:
      - "4321:80"
    depends_on:
      - pg
    logging:
      driver: none
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pg_data:
  valkey_data:
  pgadmin_data:
