services:
  valkey:
    image: valkey/valkey:8-alpine
    container_name: valkey-server
    env_file:
      - ./.env.example
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data/valkey
  pg:
    image: postgres:16-alpine
    container_name: pg-server
    env_file:
      - ./.env.example
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/data/db'
      - ./db/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - ./.env.example
    ports:
      - "54321:80"
    depends_on:
      - pg
    logging:
      driver: none
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  pg_data:
  valkey_data:
  pgadmin_data:
